// -*- mode: rust; -*-
//
// This file is part of curve25519-sol.
// Copyright (c) 2026 curve25519-sol contributors
// See LICENSE for licensing information.

//! The joint fixed-base table: each pair of radix-16 digits of tau s as one affine point.

use super::edwards_x8::ProjectiveNielsX8;
use super::field_x8::LANES;
pub(crate) use super::joint_data::JOINT_TABLE_B;

/// Table entries, one per low and high digit pair.
pub(crate) const JOINT_ENTRIES: usize = 256;

/// Affine cached points lo B + hi 2^128 B for every digit pair, limb-major for gathers
#[repr(align(64))]
pub(crate) struct JointTable {
    pub(crate) y_plus_x: [[u64; JOINT_ENTRIES]; 5],
    pub(crate) y_minus_x: [[u64; JOINT_ENTRIES]; 5],
    pub(crate) t2d: [[u64; JOINT_ENTRIES]; 5],
}

impl JointTable {
    /// Select, per lane, the entry for a joint digit, Z is one in every entry
    pub(crate) fn select(&self, index: &[u64; LANES]) -> ProjectiveNielsX8 {
        let mut out = ProjectiveNielsX8::IDENTITY;
        for (l, &j) in index.iter().enumerate() {
            let j = j as usize;
            for i in 0..5 {
                out.Y_plus_X.limbs[i][l] = self.y_plus_x[i][j];
                out.Y_minus_X.limbs[i][l] = self.y_minus_x[i][j];
                out.T2d.limbs[i][l] = self.t2d[i][j];
            }
        }
        out
    }
}

#[cfg(test)]
mod test {
    use alloc::vec::Vec;

    use super::*;
    use crate::backend::serial::u64::field::FieldElement51;
    use crate::constants::ED25519_BASEPOINT_POINT;
    use crate::edwards::EdwardsPoint;
    use crate::traits::Identity;

    /// Canonical limbs of every entry, as (y+x, y-x, 2dxy).
    fn entries() -> Vec<[[u64; 5]; 3]> {
        let canonical = |fe: &FieldElement51| FieldElement51::from_bytes(&fe.to_bytes()).0;
        let mut low = [EdwardsPoint::identity(); 16];
        let mut high = [EdwardsPoint::identity(); 16];
        let high_base = ED25519_BASEPOINT_POINT.mul_by_pow_2(128);
        for j in 1..16 {
            low[j] = low[j - 1] + ED25519_BASEPOINT_POINT;
            high[j] = high[j - 1] + high_base;
        }
        let mut out = Vec::with_capacity(JOINT_ENTRIES);
        for j in 0..JOINT_ENTRIES {
            let niels = (low[j & 15] + high[j >> 4]).as_affine_niels();
            out.push([
                canonical(&niels.y_plus_x),
                canonical(&niels.y_minus_x),
                canonical(&niels.xy2d),
            ]);
        }
        out
    }

    // the generated table holds the basepoint multiples it claims
    #[test]
    fn generated_entries() {
        for (j, entry) in entries().iter().enumerate() {
            let got: [[u64; 5]; 3] = [
                core::array::from_fn(|i| JOINT_TABLE_B.y_plus_x[i][j]),
                core::array::from_fn(|i| JOINT_TABLE_B.y_minus_x[i][j]),
                core::array::from_fn(|i| JOINT_TABLE_B.t2d[i][j]),
            ];
            assert_eq!(&got, entry, "entry {j}");
        }
    }

    // prints joint_data.rs, run with --ignored --nocapture
    #[test]
    #[ignore]
    fn print_table() {
        let entries = entries();
        std::println!("// generated by joint::test::print_table, do not edit");
        std::println!();
        std::println!("use super::joint::JointTable;");
        std::println!();
        std::println!("#[rustfmt::skip]");
        std::println!("pub(crate) static JOINT_TABLE_B: JointTable = JointTable {{");
        for (name, coord) in [("y_plus_x", 0), ("y_minus_x", 1), ("t2d", 2)] {
            std::println!("    {name}: [");
            for i in 0..5 {
                std::println!("        [");
                for chunk in entries.chunks(8) {
                    let mut line = alloc::string::String::from("           ");
                    for entry in chunk {
                        line.push_str(&alloc::format!(" {},", entry[coord][i]));
                    }
                    std::println!("{line}");
                }
                std::println!("        ],");
            }
            std::println!("    ],");
        }
        std::println!("}};");
    }
}
